import java.io.*;
import java.time.LocalDate;
import java.util.Properties;
import javax.mail.*;
import javax.mail.internet.*;
import javax.activation.*; 

public class EmailService {

    //config
    private static final String SENDER_EMAIL = "haqimnazry@gmail.com"; 
    private static final String APP_PASSWORD = "xgvg vvyb ghzv wxda"; 

    private static File generateDailyAttachment(DataManager dm) {
        LocalDate today = LocalDate.now();
        String filepath = "../sales/Daily_Report_" + today + ".txt";
        File reportFile = new File(filepath);

        double totalSales = 0.0;
        int transactionCount = 0;

        // calculate totals
        try (BufferedReader br = new BufferedReader(new FileReader("../data/sales_history.csv"))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] parts = line.split(",");
                
                if (parts.length > 0 && parts[0].equals(today.toString())) {
                    try {
                        if (parts.length >= 6) {
                            totalSales += Double.parseDouble(parts[5]); 
                            transactionCount++;
                        } 
                        // total is at index 3
                        else if (parts.length == 4) {
                            totalSales += Double.parseDouble(parts[3]); 
                            transactionCount++;
                        }
                    } catch (NumberFormatException e) {
                        //skip if unreadable
                    }
                }
            }
        } catch (IOException e) {}

        // write file
        try (PrintWriter pw = new PrintWriter(new FileWriter(reportFile))) {
            pw.println("=== DAILY SALES REPORT ===");
            pw.println("Date: " + today);
            pw.println("Transactions: " + transactionCount);
            pw.println("Total Sales: RM" + String.format("%.2f", totalSales));
            pw.println("---------------------------");
        } catch (IOException e) { return null; }
        
        return reportFile;
    }

    public static void sendDailyReport(DataManager dm, String recipientEmail) {
        System.out.println("\n... Connecting to Gmail as " + SENDER_EMAIL + " ...");

        File attachment = generateDailyAttachment(dm);
        if (attachment == null) return;

        //gmail smtp settings
        Properties props = new Properties();
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.starttls.enable", "true");
        props.put("mail.smtp.host", "smtp.gmail.com");
        props.put("mail.smtp.port", "587");
        props.put("mail.smtp.ssl.protocols", "TLSv1.2");

        Session session = Session.getInstance(props, new javax.mail.Authenticator() {
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(SENDER_EMAIL, APP_PASSWORD);
            }
        });

        try {
            Message message = new MimeMessage(session);
            message.setFrom(new InternetAddress(SENDER_EMAIL));
            message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(recipientEmail));
            message.setSubject("Daily Sales Report - " + LocalDate.now());

            Multipart multipart = new MimeMultipart();

            // Body
            BodyPart textPart = new MimeBodyPart();
            textPart.setText("Dear Student,\n\nHere is the report generated by the KedaiRuncit System.");
            multipart.addBodyPart(textPart);

            // Attachment
            BodyPart filePart = new MimeBodyPart();
            DataSource source = new FileDataSource(attachment);
            filePart.setDataHandler(new DataHandler(source));
            filePart.setFileName(attachment.getName());
            multipart.addBodyPart(filePart);

            message.setContent(multipart);

            System.out.println("Sending to: " + recipientEmail + " ...");
            Transport.send(message);
            System.out.println(">> SUCCESS: Real Email Sent Successfully!");

        } catch (AuthenticationFailedException e) {
            System.out.println(">> LOGIN FAILED: Check your App Password in EmailService.java");
        } catch (MessagingException e) {
            e.printStackTrace();
        }
    }
}